#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
nombre=$(whoami)
casa=/home/$nombre

echo -e "net.ipv6.conf.all.disable_ipv6 = 1""\n""net.ipv6.conf.default.disable_ipv6 = 1""\n""net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.d/60-disableipv6.conf
echo "* hard nproc 1000" >> /etc/security/limits.conf
echo "tmpfs /tmp tmpfs noexec,async,nosuid,noatime,nodev 0 0" >> /etc/fstab
echo "tmpfs /var/cache/samba tmpfs noatime,async,nodev 0 0" >> /etc/fstab
echo "tmpfs /var/log tmpfs noatime,async,nodev 0 0" >> /etc/fstab
echo "tmpfs /var/spool tmpfs noatime,async,nodev 0 0" >> /etc/fstab
echo "tmpfs /var/tmp tmpfs noexec,async,nosuid,noatime,nodev 0 0" >> /etc/fstab
sed -i 's/127.0.0.1	localhost/127.0.0.1	localhost $(hostname)/g' /etc/hosts



 

sed -i 's/PRELINKING=unknown/PRELINKING=yes/g' /etc/default/prelink
sed -i 's/PRELINK_OPTS=-mR/PRELINK_OPTS=-amR/g' /etc/default/prelink
prelink -amvR
/etc/cron.daily/prelink

clear
echo -e "\e[00;1;92mFinished...\e[00m"
exit 0
